version: '3.8'
services:
  workcontainer:
    container_name: workcontainer
    build:
      dockerfile: dockerfile
      args:
        - USERNAME=${USERNAME}
        - AWS_REGION=${AWS_DEFAULT_REGION}
        - EKS_NAME=${EKS_NAME}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - KUBECTL_VERSION=${KUBECTL_VERSION}
        - HELM_VERSION=${HELM_VERSION}
        - PG_CLIENT_VERSION=${PG_CLIENT_VERSION}
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - workcontainer:/work
    command: sleep infinity
  pg:
    image: postgres:15.4
    container_name: postgresdb
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: postgresadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
  chartmuseum:
    image: bitnami/chartmuseum:latest
    container_name: chartmuseum
    ports:
      - ${REGISTERY_PORT}:8080
    environment:
      DEBUG: "1"
      STORAGE: "local"
      STORAGE_LOCAL_ROOTDIR: "/bitnami/data"
    volumes:
      - chartmuseum:/bitnami/data

volumes:
  workcontainer:
  pg:
  pgadmin:
  redis:
  redis-config:
  chartmuseum:
