version: '3.8'
services:
  workcontainer:
    container_name: workcontainer
    build:
      dockerfile: dockerfile
      args:
        - USERNAME=${USERNAME}
        - KUBECTL_VERSION=${KUBECTL_VERSION}
        - HELM_VERSION=${HELM_VERSION}
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - workcontainer:/home/node/workspace
    command: sleep infinity
    network_mode: "host"
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis:/data
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    network_mode: "host"
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.12
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORT}:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    network_mode: "host"
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - ${NEO4J_PORT_1}:7687
      - ${NEO4J_PORT_2}:7474
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-conf:/conf
      - neo4j-plugins:/plugins
      - neo4j-licenses:/licenses
      - neo4j-import:/import
      - neo4j-ssl:/ssl
      - neo4j-metrics:/metrics
    network_mode: "host"
  chartmuseum:
    image: bitnami/chartmuseum:latest
    container_name: chartmuseum
    ports:
      - ${REGISTERY_PORT}:8080
    environment:
      DEBUG: '1'
      STORAGE: 'local'
      STORAGE_LOCAL_ROOTDIR: '/bitnami/data'
    volumes:
      - chartmuseum:/bitnami/data
    network_mode: "host"

volumes:
  workcontainer:
  elasticsearch-data:
  rabbitmq-data:
  neo4j-data:
  redis:
  neo4j-logs:
  neo4j-conf:
  neo4j-plugins:
  neo4j-licenses:
  neo4j-import:
  neo4j-ssl:
  neo4j-metrics:
  redis-config:
  chartmuseum:
