version: '3.8'
services:
  workcontainer:
    container_name: k-workcontainer
    build:
      dockerfile: dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - KUBECTL_VERSION=${KUBECTL_VERSION}
        - HELM_VERSION=${HELM_VERSION}
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - k-workcontainer:/home/node/workspace
    command: sleep infinity
    network_mode: 'host'

volumes:
  k-workcontainer:
  k-workcontainer-zshhistory: